development:
  login: bXXH553QL
  password: 4858g5DM65K8hUcv
test:
  login: 6uR64WvP
  password: 94G8zcPyV89m37R2
cucumber:
  login: 6uR64WvP
  password: 94G8zcPyV89m37R2
production:
  login: 6uR64WvP
  password: 94G8zcPyV89m37R2
