development:
  login: 59f5pXNh942j
  password: 95DFYL2y4je863k2
test:
  login: 59f5pXNh942j
  password: 95DFYL2y4je863k2
cucumber:
  login: 59f5pXNh942j
  password: 95DFYL2y4je863k2
production:
  login: 6uR64WvP
  password: 94G8zcPyV89m37R2
